[project]
name = "mlops-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Bogachevv"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"

[tool.poetry.dependencies]
torch = "^2.9.1"
torchvision = "^0.24.1"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
