run_name: simple-trainer
output_dir: bogachevv/simple-trainer
max_seq_length: 2048
dataset_text_field: text
fp16: true
bf16: false
full_determinism: false
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
lr_scheduler_type: linear
warmup_ratio: 0.1
num_train_epochs: 2
learning_rate: 1e-4
weight_decay: 0.01
dataloader_num_workers: 1
dataset_num_proc: 1
eval_strategy: steps
eval_steps: 128
logging_steps: 16
load_best_model_at_end: true
seed: 42
data_seed: 42
report_to: none
disable_tqdm: false
save_strategy: steps
save_steps: 128
save_total_limit: 4