ds_name: knkarthick/samsum
sys_prompt_pth: /mnt/c/Users/Vladimir/PycharmProjects/MLOps_project/prompts/samsum_sysprompt.txt
usr_prompt_pth: /mnt/c/Users/Vladimir/PycharmProjects/MLOps_project/prompts/samsum_usrprompt.txt
save_path: /mnt/c/Users/Vladimir/PycharmProjects/MLOps_project/datasets/samsum